################################################
# Make file generated by HEW
#

############################
# Toolchain directory define
# If incorrect, change to the location of the Renesas M32R Standard Toolchain toolchain
TC_INSTALL_DIR = C:\\Renesas\\cc32r\\v501r01

###############################################################################
# The following environment variables are for building the makefile inside HEW:
# INC32R=C:\Renesas\cc32r\v501r01\inc32r
# M32RLIB=C:\Renesas\cc32r\v501r01\lib32r
# PATH=C:\Renesas\cc32r\v501r01\bin32r;C:\Renesas\cc32r\v501r01\bin
# M32RTMP=C:\Renesas\cc32r\v501r01\TMP
# M32RBIN=C:\Renesas\cc32r\v501r01\bin32r
# LIB32R=C:\Renesas\cc32r\v501r01\lib32r
# M32RINC=C:\Renesas\cc32r\v501r01\inc32r
#

#####################################################
#
# Details:
#   Project: Shifter
#   Configuration: Release
#   Toolchain: Renesas M32R Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas M32R C Compiler01 phase

SHIFTER_RELEASE_M32R_C_COMPILER01_EXE=cc32r.exe
SHIFTER_RELEASE_M32R_C_COMPILER01_EXEDIR=$(TC_INSTALL_DIR)\\bin32r
SHIFTER_RELEASE_M32R_C_COMPILER01_OUTFILESC0=.\\build\\shifter.mo

# Renesas M32R Assembler02 phase

SHIFTER_RELEASE_M32R_ASSEMBLER02_EXE=as32r.exe

# Renesas M32R Linker03 phase

SHIFTER_RELEASE_M32R_LINKER03_OUTFILESC0=.\\build\\shifter.abs
SHIFTER_RELEASE_M32R_LINKER03_DEPFILESC0=$(TC_INSTALL_DIR)\\lib32r\\m32RcR.lib

# Renesas M32R Stype Converter04 phase

SHIFTER_RELEASE_M32R_LOAD_MODULE_CONVERTER04_EXE=lmc32r.exe
SHIFTER_RELEASE_M32R_LOAD_MODULE_CONVERTER04_OUTFILESC0=.\\build\\shifter.mot

#######################
# nmake "all" statement

ALL:	$(SHIFTER_RELEASE_M32R_C_COMPILER01_OUTFILESC0) \
	$(SHIFTER_RELEASE_M32R_LINKER03_OUTFILESC0) \
	$(SHIFTER_RELEASE_M32R_LOAD_MODULE_CONVERTER04_OUTFILESC0)

####################
# Description blocks

#
# Executing Renesas M32R C Compiler01 phase
#

$(SHIFTER_RELEASE_M32R_C_COMPILER01_OUTFILESC0) : .\\shifter.c
	$(SHIFTER_RELEASE_M32R_C_COMPILER01_EXE) -c -o .\\build\\shifter.mo -small -lang=c -O0 -MAP .\\build\\shifter.map .\\shifter.c

#
# Executing Renesas M32R Linker03 phase
#

$(SHIFTER_RELEASE_M32R_LINKER03_OUTFILESC0) : $(SHIFTER_RELEASE_M32R_C_COMPILER01_OUTFILESC0) $(SHIFTER_RELEASE_M32R_LINKER03_DEPFILESC0)
	$(SHIFTER_RELEASE_M32R_C_COMPILER01_EXE) \
	-o .\\build\\shifter.abs \
	-MAP .\\build\\shifter.map \
	-SEC CONST_DATA=05D900,CODE=05DA00,RAM_DATA=806900 \
	.\\build\shifter.mo

#
# Executing Renesas M32R Stype Converter04 phase
#

$(SHIFTER_RELEASE_M32R_LOAD_MODULE_CONVERTER04_OUTFILESC0) : $(SHIFTER_RELEASE_M32R_LINKER03_OUTFILESC0)
	$(SHIFTER_RELEASE_M32R_LOAD_MODULE_CONVERTER04_EXE) -o .\\build\\shifter.mot .\\build\\shifter.abs

